import { Router } from "express";
import auth from "../modules/auth/routes";
import customers from "../modules/customers/routes";
import medicines from "../modules/medicines/routes";
import cart from "../modules/cart/routes";
import orders from "../modules/orders/routes";
import prescriptions from "../modules/prescriptions/routes";
import adminPrescriptions from "../modules/admin/prescriptions";
import catalog from "../modules/catalog/routes";
import payments from "../modules/payments/routes";
import delivery from "../modules/delivery/routes";
const router=Router();
router.use("/auth",auth);
router.use("/customers",customers);
router.use("/medicines",medicines);
router.use("/cart",cart);
router.use("/orders",orders);
router.use("/admin/catalog",catalog);
router.use("/admin",adminPrescriptions);
router.use("/payments",payments);
router.use("/delivery",delivery);
export default router;
